### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by nx10** [nx10/httpgd#25]
This is a tracking issue for major tasks that have to be done for a 1.0.0 release. The goal is to ship a reliable and fast graphics device and a HTML/JS client that is easy to use. 
Bugfixes and small feature requests will also be worked on when they arise.

**Backend**
- [x] Use [Boost Beast](https://github.com/boostorg/beast)
  - [x] Get beast servers (http & websocket) to compile + run in an R package ([done!](https://github.com/nx10/r-boost-beast-example))
  - [x] Switch from `cpphttplib` server to beast
  - [x] Implement websockets
- [x] Unit tests (If you want to contribute, this would be a great way to start)
- [x] Generate better SVGs
  - [x] Improve SVG rendering (Number formatting, string building, ...)
- [x] Offline mode

**HTML/JS Client**
- [x] Handle websockets (and optionally polling, if ws are not available)
- [x] Display disconnected status (https://github.com/nx10/httpgd/issues/23)
- [x] Render PNG / raster graphics (https://github.com/nx10/httpgd/issues/9)

**Other**
- [x] Create logo
- [x] Investigate build and R CMD CHECK output for all platforms (Win, Linux, macOS)
- [x] Clean up code & meta data
- [x] Release 1.0.0 to CRAN

**After 1.0**
- [x] Improve documentation
- [ ] Replace Belle (might not be necessary: https://github.com/octobanana/belle/issues/13)
- [x] Consider switching from `Rcpp` to [`cpp11`](https://github.com/r-lib/cpp11)
- [ ] Analyze draw call data to generate small optimized SVGs

**Comment by nx10** [comment]
Just a small update on this: The only thing blocking CRAN release right now is [this](https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006335.html) CMD check warning which only happens with the Windows build. My best guess is that it is caused by the way I had to combine the boost beast headers with the boost headers of the `BH` package.

I hope this will be resolved with the next `BH` update (https://github.com/nx10/httpgd/issues/40), which will probably happen a couple days after boost 1.75 releases [this week](https://www.boost.org/development/index.html).

**Comment by nx10** [comment]
Another update: The new `BH` version will be out in January. I got the development version from GitHub (after some fixes to Belle) working and was able to run httpgd without any additional boost headers. The bad news is that the compiler warning persists. I will now try a couple of things to isolate the problem, if those fails as well, I will try to contact the CRAN team directly.

**Comment by nx10** [comment]
It's out now: https://cran.r-project.org/package=httpgd
